package Vista;

import Controlador.*;
import Modelo.*;
import javax.swing.JButton;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author mnieves.domnav
 */
public class Vista extends javax.swing.JFrame implements InterfazVista {

    private Controlador ctrl;

    /**
     * Creates new form Interfaz
     */
    public Vista() {
        initComponents();

    }

    @Override
    public void setControlador(Controlador c) {
        this.ctrl = c;
        mPedido.setActionCommand("cambio");
        mPedido.addActionListener(c);

        //Botones de las recetas en cocina
        JButton[] recetas = {
            cReceta0, cReceta1, cReceta2, cReceta3, cReceta4, cReceta5,
            cReceta6, cReceta7, cReceta8, cReceta9, cReceta10, cReceta11
        };

        for (JButton btn : recetas) {
            btn.setActionCommand("agregar"); //
            btn.addActionListener(c);
        }

        cEntrega1.setActionCommand("quitar");
        cEntrega1.addActionListener(c);
        cEntrega2.setActionCommand("quitar");
        cEntrega2.addActionListener(c);
        cEntrega3.setActionCommand("quitar");
        cEntrega3.addActionListener(c);
        cServir.setActionCommand("servir");
        cServir.addActionListener(c);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Mostrador = new javax.swing.JPanel();
        mNombreCliente = new javax.swing.JLabel();
        mCliente = new javax.swing.JLabel();
        mPedido = new javax.swing.JButton();
        mDinero = new javax.swing.JLabel();
        Cocina = new javax.swing.JPanel();
        cAreaDeEntrega = new javax.swing.JPanel();
        cEntrega1 = new javax.swing.JButton();
        cEntrega2 = new javax.swing.JButton();
        cEntrega3 = new javax.swing.JButton();
        cServir = new javax.swing.JButton();
        cCliente = new javax.swing.JComboBox<>();
        cAreaDeRecetas = new javax.swing.JPanel();
        cReceta0 = new javax.swing.JButton();
        cReceta1 = new javax.swing.JButton();
        cReceta2 = new javax.swing.JButton();
        cReceta3 = new javax.swing.JButton();
        cReceta4 = new javax.swing.JButton();
        cReceta5 = new javax.swing.JButton();
        cReceta6 = new javax.swing.JButton();
        cReceta7 = new javax.swing.JButton();
        cReceta8 = new javax.swing.JButton();
        cReceta9 = new javax.swing.JButton();
        cReceta10 = new javax.swing.JButton();
        cReceta11 = new javax.swing.JButton();
        cDinero = new javax.swing.JLabel();
        Pedidos = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pPedidos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mNombreCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mNombreCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mNombreCliente.setText("Nombre del cliente");

        mCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mCliente.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        mPedido.setBorderPainted(false);
        mPedido.setContentAreaFilled(false);

        mDinero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mDinero.setText("Dinero: 0€");

        javax.swing.GroupLayout MostradorLayout = new javax.swing.GroupLayout(Mostrador);
        Mostrador.setLayout(MostradorLayout);
        MostradorLayout.setHorizontalGroup(
            MostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MostradorLayout.createSequentialGroup()
                .addGroup(MostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostradorLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(mCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MostradorLayout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(mNombreCliente))
                    .addGroup(MostradorLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(mDinero)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        MostradorLayout.setVerticalGroup(
            MostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MostradorLayout.createSequentialGroup()
                .addGroup(MostradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MostradorLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(mPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(MostradorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mDinero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                        .addComponent(mCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(mNombreCliente)
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Mostrador", Mostrador);

        cAreaDeEntrega.setBackground(new java.awt.Color(204, 255, 255));

        cEntrega1.setBorderPainted(false);
        cEntrega1.setContentAreaFilled(false);
        cEntrega1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cEntrega2.setBorderPainted(false);
        cEntrega2.setContentAreaFilled(false);
        cEntrega2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        cEntrega3.setBorderPainted(false);
        cEntrega3.setContentAreaFilled(false);

        cServir.setText("Entregar");

        javax.swing.GroupLayout cAreaDeEntregaLayout = new javax.swing.GroupLayout(cAreaDeEntrega);
        cAreaDeEntrega.setLayout(cAreaDeEntregaLayout);
        cAreaDeEntregaLayout.setHorizontalGroup(
            cAreaDeEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cAreaDeEntregaLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(cEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cEntrega3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cAreaDeEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cAreaDeEntregaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                        .addComponent(cServir, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(cAreaDeEntregaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        cAreaDeEntregaLayout.setVerticalGroup(
            cAreaDeEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cAreaDeEntregaLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(cAreaDeEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cAreaDeEntregaLayout.createSequentialGroup()
                        .addComponent(cCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cServir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, cAreaDeEntregaLayout.createSequentialGroup()
                        .addGroup(cAreaDeEntregaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cEntrega2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cEntrega3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cEntrega1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
        );

        cReceta0.setText("Receta");

        cReceta1.setText("Receta");

        cReceta2.setText("Receta");

        cReceta3.setText("Receta");

        cReceta4.setText("Receta");

        cReceta5.setText("Receta");

        cReceta6.setText("Receta");

        cReceta7.setText("Receta");

        cReceta8.setText("Receta");

        cReceta9.setText("Receta");

        cReceta10.setText("Receta");

        cReceta11.setText("Receta");

        javax.swing.GroupLayout cAreaDeRecetasLayout = new javax.swing.GroupLayout(cAreaDeRecetas);
        cAreaDeRecetas.setLayout(cAreaDeRecetasLayout);
        cAreaDeRecetasLayout.setHorizontalGroup(
            cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cAreaDeRecetasLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cReceta2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cReceta5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cReceta8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cReceta11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cAreaDeRecetasLayout.setVerticalGroup(
            cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cAreaDeRecetasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cAreaDeRecetasLayout.createSequentialGroup()
                        .addComponent(cReceta1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cReceta0, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cAreaDeRecetasLayout.createSequentialGroup()
                        .addComponent(cReceta3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cReceta4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cAreaDeRecetasLayout.createSequentialGroup()
                        .addComponent(cReceta9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cReceta10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cAreaDeRecetasLayout.createSequentialGroup()
                        .addComponent(cReceta6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cReceta7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cAreaDeRecetasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cReceta11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cReceta2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        cDinero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cDinero.setText("Dinero: 0€");

        javax.swing.GroupLayout CocinaLayout = new javax.swing.GroupLayout(Cocina);
        Cocina.setLayout(CocinaLayout);
        CocinaLayout.setHorizontalGroup(
            CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cAreaDeRecetas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cAreaDeEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(CocinaLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cDinero)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CocinaLayout.setVerticalGroup(
            CocinaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CocinaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cDinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(cAreaDeRecetas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cAreaDeEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Cocina", Cocina);

        pPedidos.setEditable(false);
        pPedidos.setColumns(20);
        pPedidos.setRows(5);
        jScrollPane1.setViewportView(pPedidos);

        javax.swing.GroupLayout PedidosLayout = new javax.swing.GroupLayout(Pedidos);
        Pedidos.setLayout(PedidosLayout);
        PedidosLayout.setHorizontalGroup(
            PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );
        PedidosLayout.setVerticalGroup(
            PedidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PedidosLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Pedidos", Pedidos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cocina;
    private javax.swing.JPanel Mostrador;
    private javax.swing.JPanel Pedidos;
    private javax.swing.JPanel cAreaDeEntrega;
    private javax.swing.JPanel cAreaDeRecetas;
    public javax.swing.JComboBox<String> cCliente;
    public javax.swing.JLabel cDinero;
    public javax.swing.JButton cEntrega1;
    public javax.swing.JButton cEntrega2;
    public javax.swing.JButton cEntrega3;
    public javax.swing.JButton cReceta0;
    public javax.swing.JButton cReceta1;
    public javax.swing.JButton cReceta10;
    public javax.swing.JButton cReceta11;
    public javax.swing.JButton cReceta2;
    public javax.swing.JButton cReceta3;
    public javax.swing.JButton cReceta4;
    public javax.swing.JButton cReceta5;
    public javax.swing.JButton cReceta6;
    public javax.swing.JButton cReceta7;
    public javax.swing.JButton cReceta8;
    public javax.swing.JButton cReceta9;
    public javax.swing.JButton cServir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JLabel mCliente;
    public javax.swing.JLabel mDinero;
    public javax.swing.JLabel mNombreCliente;
    public javax.swing.JButton mPedido;
    public javax.swing.JTextArea pPedidos;
    // End of variables declaration//GEN-END:variables

    @Override
    public void arranca() {
        pack(); // Coloca los componentes
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
        setVisible(true); // Visualiza la ventana
    }

}
